set_property PACKAGE_PIN V17 [get_ports {tb}]
    set_property IOSTANDARD LVCMOS33 [get_ports {tb}]
set_property PACKAGE_PIN V16 [get_ports {ta}]
    set_property IOSTANDARD LVCMOS33 [get_ports {ta}]
set_property PACKAGE_PIN W16 [get_ports {masa}]
    set_property IOSTANDARD LVCMOS33 [get_ports {masa}]
set_property PACKAGE_PIN W17 [get_ports {alarm}]
    set_property IOSTANDARD LVCMOS33 [get_ports {alarm}]