webtalk_init -webtalk_dir /home/vmrod/devel/vivado/abs_5/abs_5.sim/sim_1/behav/xsim/xsim.dir/abs_5_TB_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Jul 10 07:26:09 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "212238188_0_0_004" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "744c9114-614a-45f6-a02f-35fc0b595572" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "f355658a7e714c99bec2d1efa35d29d8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "unknown" -context "user_environment"
webtalk_add_data -client project -key os_release -value "unknown" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8809G CPU @ 3.10GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "4071.386 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "33.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.05_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "125544_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3018242176 -regid "212238188_0_0_004" -xml /home/vmrod/devel/vivado/abs_5/abs_5.sim/sim_1/behav/xsim/xsim.dir/abs_5_TB_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/vmrod/devel/vivado/abs_5/abs_5.sim/sim_1/behav/xsim/xsim.dir/abs_5_TB_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/vmrod/devel/vivado/abs_5/abs_5.sim/sim_1/behav/xsim/xsim.dir/abs_5_TB_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
